apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: helpdesk-backend
  namespace: chamados-cematel
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: helpdesk-backend
          port: 80