apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waha-sessions
  namespace: chamados-cematel
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi