apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: chamados-cematel-homolog
stringData:
  POSTGRES_USER: helpdesk_app
  POSTGRES_PASSWORD: 2L9y+PZYcESSYe1jbaSUGdnVYXEs5LPW
  POSTGRES_DB: helpdesk