"""adicionar tabela de anexos

Revision ID: 7aa1f16608a7
Revises: 2a76f2a9348e
Create Date: 2026-08-13 15:58:26.279455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa1f16608a7'
down_revision = '2a76f2a9348e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chamado_contador_diario')
    op.drop_constraint('uq_chamado_numero_chamado', 'chamado', type_='unique')
    op.create_index(op.f('ix_chamado_numero_chamado'), 'chamado', ['numero_chamado'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chamado_numero_chamado'), table_name='chamado')
    op.create_unique_constraint('uq_chamado_numero_chamado', 'chamado', ['numero_chamado'])
    op.create_table('chamado_contador_diario',
    sa.Column('data', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('contador', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('data', name='chamado_contador_diario_pkey')
    )
    # ### end Alembic commands ###