"""adicionar tabela de anexos

Revision ID: c5a7a42601aa
Revises: 7aa1f16608a7
Create Date: 2026-08-13 22:58:28.176733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a7a42601aa'
down_revision = '7aa1f16608a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chamado_anexo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamado_id', sa.Integer(), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('nome_armazenado', sa.String(length=255), nullable=False),
    sa.Column('tipo_mime', sa.String(length=100), nullable=False),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=False),
    sa.Column('enviado_por_codigo', sa.Integer(), nullable=False),
    sa.Column('enviado_por_nome_snapshot', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chamado_anexo_chamado_id'), 'chamado_anexo', ['chamado_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chamado_anexo_chamado_id'), table_name='chamado_anexo')
    op.drop_table('chamado_anexo')
    # ### end Alembic commands ###