"""admin: contatos, sla por prioridade, status finalizador

Revision ID: d280b941f6a9
Revises: abde8296327f
Create Date: 2026-08-16 17:37:49.396957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd280b941f6a9'
down_revision = 'abde8296327f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_contato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_codigo', sa.Integer(), nullable=False),
    sa.Column('usuario_nome_snapshot', sa.String(length=255), nullable=False),
    sa.Column('whatsapp_numero', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_contato_usuario_codigo'), 'usuario_contato', ['usuario_codigo'], unique=True)
    op.add_column('prioridade', sa.Column('sla_horas', sa.Integer(), nullable=False, server_default='24'))
    op.add_column('status', sa.Column('finalizador', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status', 'finalizador')
    op.drop_column('prioridade', 'sla_horas')
    op.drop_index(op.f('ix_usuario_contato_usuario_codigo'), table_name='usuario_contato')
    op.drop_table('usuario_contato')
    # ### end Alembic commands ###
