"""criacao inicial das tabelas de chamados

Revision ID: de4b99d93b54
Revises: 
Create Date: 2026-08-11 18:55:40.069304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de4b99d93b54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('prioridade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('cor', sa.String(length=7), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('cor', sa.String(length=7), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('chamado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_codigo', sa.Integer(), nullable=False),
    sa.Column('cliente_nome_snapshot', sa.String(length=255), nullable=False),
    sa.Column('cliente_contato_snapshot', sa.String(length=255), nullable=True),
    sa.Column('cliente_telefone_snapshot', sa.String(length=50), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('prioridade_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_codigo', sa.Integer(), nullable=True),
    sa.Column('responsavel_nome_snapshot', sa.String(length=255), nullable=True),
    sa.Column('criado_por_codigo', sa.Integer(), nullable=False),
    sa.Column('criado_por_nome_snapshot', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolvido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('encerrado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['prioridade_id'], ['prioridade.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chamado_cliente_codigo'), 'chamado', ['cliente_codigo'], unique=False)
    op.create_index(op.f('ix_chamado_criado_por_codigo'), 'chamado', ['criado_por_codigo'], unique=False)
    op.create_index(op.f('ix_chamado_responsavel_codigo'), 'chamado', ['responsavel_codigo'], unique=False)
    op.create_table('chamado_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamado_id', sa.Integer(), nullable=False),
    sa.Column('usuario_codigo', sa.Integer(), nullable=False),
    sa.Column('usuario_nome_snapshot', sa.String(length=255), nullable=False),
    sa.Column('campo_alterado', sa.String(length=50), nullable=False),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_novo', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chamado_historico_chamado_id'), 'chamado_historico', ['chamado_id'], unique=False)
    op.create_table('chamado_interacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamado_id', sa.Integer(), nullable=False),
    sa.Column('usuario_codigo', sa.Integer(), nullable=False),
    sa.Column('usuario_nome_snapshot', sa.String(length=255), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chamado_interacao_chamado_id'), 'chamado_interacao', ['chamado_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chamado_interacao_chamado_id'), table_name='chamado_interacao')
    op.drop_table('chamado_interacao')
    op.drop_index(op.f('ix_chamado_historico_chamado_id'), table_name='chamado_historico')
    op.drop_table('chamado_historico')
    op.drop_index(op.f('ix_chamado_responsavel_codigo'), table_name='chamado')
    op.drop_index(op.f('ix_chamado_criado_por_codigo'), table_name='chamado')
    op.drop_index(op.f('ix_chamado_cliente_codigo'), table_name='chamado')
    op.drop_table('chamado')
    op.drop_table('status')
    op.drop_table('prioridade')
    op.drop_table('categoria')
    # ### end Alembic commands ###